package com.iwedia.cltv.platform.model.information_bus.events

/**
 * Event ids
 *
 * @author Dejan Nadj
 */
object Events {
    const val APP_INITIALIZED = 1
    const val CHANNELS_LOADED = 20
    const val EVENTS_LOADED = 21
    const val CHANNEL_CHANGED = 22
    const val SHOW_NOTIFICATION = 23
    const val BLUETOOTH_DEVICE_FOUND = 24
    const val LANGUAGE_CHANGED = 25
    const val PVR_RECORDING_REMOVED = 33
    const val PVR_RECORDING_RENAMED = 34
    const val START_TV_INPUT_SETUP_ACTIVITY = 35

    const val NETWORK_AVAILABILITY = 100
    const val NO_PLAYBACK = 101
    const val PLAYER_TIMEOUT = 102
    const val PLAYBACK_BUFFERING = 103
    const val PLAYBACK_STARTED = 104
    const val SCRAMBLED_STATUS = 106
    const val PLAYBACK_STOPPED = 165
    const val PLAYBACK_INIT = 1000004

    const val WAITING_FOR_CHANNEL = 105
    const val SCRAMBLED_CHANNEL = 106
    const val NO_CHANNELS_AVAILABLE = 107
    const val CHANNELS_AVAILABLE = 108
    const val PARENTAL_PIN_SHOW = 109
    const val PARENTAL_PIN_HIDE = 110
    const val DRM_ERROR = 111
    const val DRM_SUCCESS = 112
    const val NETWORK_UNAVAILABILITY = 114
    const val AUDIO_TRACKS_UPDATED = 115
    const val SUBTITLE_TRACKS_UPDATED = 116
    const val PROCEED_CLICKED = 117
    const val TIME_SHIFT_POSITION_EVENT = 119

    const val SHOW_STOP_TIME_SHIFT_DIALOG = 120
    const val SHOW_RECORDING_TIME_SHIFT_CONFLICT_DIALOG = 121
    const val SHOW_WATCHLIST_TIME_SHIFT_CONFLICT_DIALOG = 122

    const val NO_INTERNET_EVENT = 124

    const val AUDIO_TRACKS_SCENE_REFRESH = 125
    const val SUBTITLE_TRACKS_SCENE_REFRESH = 126
    const val REFRESH_ZAP_BANNER = 127

    const val NETWORK_STATE_CHANGED_EVENT = 128
    const val NO_ETHERNET_EVENT = 129
    const val ETHERNET_EVENT = 130
    const val ACTIVE_CHANNEL_LOCKED_EVENT = 131

    const val SHOW_STOP_RECORDING_DIALOG = 132
    const val ACTIVE_CHANNEL_DELETED_EVENT = 133
    const val SHOW_PLAYER_BANNER_EVENT = 134
    const val CHANNEL_LIST_IS_EMPTY = 135
    const val ACTIVE_CHANNEL_UNLOCKED_EVENT = 136

    const val ACTIVE_SERVICE_NOT_RUNNING = 137
    const val ACTIVE_SERVICE_REPLACEABLE = 138
    const val ACTIVE_SERVICE_RUNNING = 139
    const val CHANNEL_LIST_UPDATED = 140
    const val FAVORITE_LIST_UPDATED = 141
    const val FAVORITE_LIST_CATEGORY_UPDATED = 142
    const val RECENTLY_WATCHED_UPDATED = 143
    const val EPG_DATA_UPDATED = 144
    const val SHOW_PLAYER_SUBTITLE_LIST = 145
    const val PVR_PLAYING = 146
    const val SHOW_PLAYER_AUDIO_LIST = 147
    const val SHOW_PLAYER = 148
    const val REFRESH_FOR_YOU = 149
    const val REFRESH_EPG = 150
    const val SHOW_PVR_CONFLICT_SCENE = 151
    const val PREFERENCE_DELETE_CHANNEL = 152
    const val PREFERENCE_CLEAR_ALL_CHANNELS = 153
    const val IS_EAS_PLAYING = 154
    const val TIME_CHANGED = 155
    const val VIDEO_RESOLUTION_AVAILABLE = 156
    const val UPDATE_WATCHLIST_INDICATOR = 157
    const val EXIT_APPLICATION_ON_SCAN = 158
    const val RECHECK_APP_PERMISSIONS = 159
    const val EXIT_APPLICATION_ON_BACK_PRESS = 160
    const val VIDEO_RESOLUTION_UNAVAILABLE = 161
    const val GET_INPUT_RESOLUTION_DATA = 162
    const val CLOSED_CAPTION_CHANGED = 163
    const val SUBTITLE_TRACK_SELECTED = 164
    const val UPDATE_REC_LIST_INDICATOR = 166
    const val TIME_CHANGED_IN_TIMESHIFT = 167
    const val SET_FILE_TO_USB = 168
    const val START_USB_FORMATING = 169
    const val STOP_TIMESHIFT = 170
    const val CHANNEL_LIST_SWITCHED = 171
    const val SHOW_DEVICE_INFO = 172

    const val PLAYBACK_STATUS_MESSAGE_NONE = 500
    const val PLAYBACK_SHOW_BLACK_OVERLAY = 501
    const val PLAYBACK_HIDE_BLACK_OVERLAY = 502
    const val PLAYBACK_STATUS_MESSAGE_IS_RADIO = 503
    const val PLAYBACK_STATUS_MESSAGE_IS_SCRAMBLED = 504
    const val PLAYBACK_STATUS_MESSAGE_IS_LOCKED = 505
    const val PLAYBACK_STATUS_MESSAGE_IS_NOT_LOCKED = 506
    const val PLAYBACK_STATUS_MESSAGE_IS_PARENTAL = 507
    const val PLAYBACK_STATUS_MESSAGE_IS_NOT_PARENTAL = 508
    const val PLAYBACK_STATUS_MESSAGE_IS_MESSAGE = 509
    const val PLAYBACK_STATUS_MESSAGE_IS_RUNNING = 510
    const val PLAYBACK_STATUS_MESSAGE_IS_NOT_RUNNING = 511
    const val PLAYBACK_STATUS_MESSAGE_IS_REPLACEABLE = 512
    const val PLAYBACK_STATUS_MESSAGE_UNLOCK_PRESSED = 513
    const val PLAYBACK_STATUS_MESSAGE_PVR_UNLOCK = 514
    const val PLAYBACK_STATUS_MESSAGE_PVR_LOCK = 515
    const val PLAYBACK_STATUS_MESSAGE_NO_SIGNAL = 516
    const val PLAYBACK_STATUS_MESSAGE_NO_PLAYBACK = 517
    const val SCHEDULED_RECORDING_REMINDER_CONFLICTS_NOTIFICATION= 559
    const val PLAYBACK_STATUS_MESSAGE_PARENTAL_UNLOCK_PRESSED = 560
    const val ZAP_ON_GUIDE_ONLY = 561


    const val OVERLAY_FEATURE_VIEW_SHOW = 601
    const val OVERLAY_FEATURE_VIEW_HIDE = 602
    const val OVERLAY_FEATURE_VIEW_INIT = 603
    const val OVERLAY_FEATURE_VIEW_LOAD = 604

    const val DISK_READY_EVENT = 700

    const val SEARCH_CHANNELS_RESULT = 990

    const val SCHEDULED_RECORDING_CONFLICT = 550
    const val SCHEDULED_RECORDING_NOTIFICATION = 551
    const val SCHEDULED_RECORDING_NOTIFICATION_START= 557
    const val SCHEDULED_RECORDING_REMOVED = 552
    const val SCHEDULED_REMINDER_ADD = 553
    const val SCHEDULED_REMINDER_REMOVED = 555
    const val WATCHLIST_SCHEDULED_TOAST = 558


    const val SCHEDULED_REMINDER_NOTIFICATION = 123

    const val USB_DRIVE_FULL = 8998
    const val USB_DEVICE_CONNECTED = 9889
    const val USB_DEVICE_DISCONNECTED = 8989
    const val PVR_RECORDING_STARTED = 9989
    const val PVR_RECORDING_FINISHED = 9990
    const val PVR_RECORDING_FINISHING = 9991
    const val PVR_RECORDING_STARTING = 9992
    const val PVR_RECORDING_SHOULD_STOP = 9993
    const val PVR_PLAYBACK_STARTED = 9999
    const val PVR_PLAYBACK_STOPPED = 9998
    const val PVR_RECORDING_INTERRUPTED = 9997
    const val REFRESH_PVR_BANNER = 7899
    const val SHOW_PVR_BANNER = 540
    const val RCU_DIGIT_PRESSED = 541
    const val RCU_PERIOD_PRESSED = 542
    const val SDK_POST_INIT_FINISHED = 777

    const val FOCUS_ON_BACK_PRESS = 778

    const val RECORDING_SCHEDULED_TOAST = 556
    const val TESTING_FINISHED = 2319

    const val UPDATE_INFO_BANNER = 4876
    const val ACTIVE_AUDIO_TRACK_REFRESHED = 4877
    const val VIDEO_ASPECT_RATION = 5001
    const val RECORDING_RENAMED = 10100
    const val UPDATED_CONFIG_KEYS = 4877


    const val UPDATED_EPGDATAHELPER = 10000
    const val RECORDING_REMOVED = 10200
    const val SHOW_INTERRUPTED_RECORDING_DIALOG = 10300
    const val SHOW_USB_FULL_DIALOG = 10400
    const val SHOW_PVR_USB_ERROR_DIALOG = 10500
    const val LAUNCH_INPUT_HOME = 10600
    const val BLOCK_TV_VIEW = 10700
    const val UNBLOCK_TV_VIEW = 10800
    const val WATCHLIST_INPUT = 10900



    const val BLUE_MUTE_ENABLED = 11000
    const val NO_SIGNAL_POWER_OFF_ENABLED = 11100
    const val NO_SIGNAL_POWER_OFF_TIME_CHANGED = 11200
    const val NO_SIGNAL_POWER_OFF_TIMER_END = 11300
    const val INACTIVITY_TIMER_END = 12000
    const val NO_AV_OR_AUDIO_ONLY_CHANNEL = 12001
    const val APP_STOPPED = 12002
    const val FAST_FAVORITES_COLLECTED = 12003
    const val FAST_DATA_UPDATED = 12004
    const val WATCHLIST_RESTORED = 12005
    const val ANOKI_SERVER_REACHABLE = 12006
    const val ANOKI_SERVER_NOT_REACHABLE = 12007
    const val HANDLE_INPUT_CEC_TUNE = 12008
    const val TALKBACK_CLOSE_ZAP_BANNER = 12009
    const val TOS_ACCEPTED = 12010
    const val ANOKI_RATING_LEVEL_CHANGED = 12011
    const val SHOW_ANOKI_MODE_TOAST = 12012
    const val ANOKI_RATING_LEVEL_SET = 12013
    const val ANOKI_CHANNEL_LIST_REORDERED = 12014
    const val ANOKI_CHANNEL_LIST_REORDER_FINISHED = 12015
    const val ANOKI_REGION_NOT_SUPPORTED = 12016
    const val SHOW_NEW_CHANNELS_FOUND_POPUP = 12017
    const val SHOW_CHANNEL_CHANGE_TOAST_FOR_T56 = 12018

    const val DIRECT_TUNE_FORCE_PLAYBACK = 13001

    const val VOD_CURRENT_POSITION = 13002
    const val VOD_PLAYER_STATE = 13003
    const val VOD_PLAY_BACK_ERROR = 13004
    const val VOD_PLAY_STATE = 13005
    const val VOD_PAUSE_STATE = 13006
    const val VOD_SEEK_TO_STATE = 13007
    const val VOD_STOP_STATE = 13008
    const val VOD_RELEASE_STATE = 13009
    const val VOD_START_TIMER = 13010
    const val VOD_STOP_TIMER = 13011
    const val VOD_FORWARD_STATE = 13012
    const val VOD_BACKWARD_STATE = 13013
    const val VOD_DURATION_POSITION = 13014
    const val VOD_ON_START = 13017

    const val MAL_SERVICE_HBB_TV_SET_SURFACE = 14000
    const val MAL_SERVICE_HBB_TV_VISIBILITY_CHANGE = 14001
    const val MAL_SERVICE_HBB_TV_REGION_CHANGE = 14002
    const val FOR_YOU_NOW_NEXT_UPDATED = 14003
    const val GOOGLE_PIN_CORRECT = 59
    const val VOD_PLAYBACK_STARTED = 13015
    const val VOD_CONTENT_IS_WATCHED = 13016
}