package com.iwedia.cltv.sdk

object ReferenceEvents {
    const val NETWORK_AVAILABILITY = 100
    const val NO_PLAYBACK = 101
    const val PLAYER_TIMEOUT = 102
    const val PLAYBACK_BUFFERING = 103
    const val PLAYBACK_STARTED = 104
    const val PLAYBACK_INIT = 1000004

    const val WAITING_FOR_CHANNEL = 105
    const val SCRAMBLED_CHANNEL = 106
    const val NO_CHANNELS_AVAILABLE = 107
    const val CHANNELS_AVAILABLE = 108
    const val PARENTAL_PIN_SHOW = 109
    const val PARENTAL_PIN_HIDE = 110
    const val DRM_ERROR = 111
    const val DRM_SUCCESS = 112
    const val APP_INITIALIZED = 113
    const val NETWORK_UNAVAILABILITY = 114
    const val AUDIO_TRACKS_UPDATED = 115
    const val SUBTITLE_TRACKS_UPDATED = 116
    const val PROCEED_CLICKED = 117
    const val TIME_SHIFT_POSITION_EVENT = 119
    const val NO_INTERNET_EVENT = 124

    const val AUDIO_TRACKS_SCENE_REFRESH = 125
    const val SUBTITLE_TRACKS_SCENE_REFRESH = 126
    const val REFRESH_ZAP_BANNER = 127

    const val NETWORK_STATE_CHANGED_EVENT = 128
    const val NO_ETHERNET_EVENT = 129
    const val ETHERNET_EVENT = 130
    const val ACTIVE_CHANNEL_LOCKED_EVENT = 131

    const val SHOW_STOP_RECORDING_DIALOG = 132
    const val SHOW_STOP_TIME_SHIFT_DIALOG = 132
    const val ACTIVE_CHANNEL_DELETED_EVENT = 133
    const val SHOW_PLAYER_BANNER_EVENT = 134
    const val CHANNEL_LIST_IS_EMPTY = 135
    const val ACTIVE_CHANNEL_UNLOCKED_EVENT = 136

    const val ACTIVE_SERVICE_NOT_RUNNING = 137
    const val ACTIVE_SERVICE_REPLACEABLE = 138
    const val ACTIVE_SERVICE_RUNNING = 139
    const val CHANNEL_LIST_UPDATED = 140
    const val FAVORITE_LIST_UPDATED = 141
    const val FAVORITE_LIST_CATEGORY_UPDATED = 142
    const val RECENTLY_WATCHED_UPDATED = 143
    const val EPG_DATA_UPDATED = 144
    const val SHOW_PLAYER_SUBTITLE_LIST = 145
    const val PVR_PLAYING = 146
    const val SHOW_PLAYER_AUDIO_LIST = 147
    const val SHOW_PLAYER = 148
    const val REFRESH_FOR_YOU = 149
    const val SHOW_PVR_CONFLICT_SCENE = 151


    const val PLAYBACK_STATUS_MESSAGE = 500
    const val PLAYBACK_SHOW_BLACK_OVERLAY = 501
    const val PLAYBACK_HIDE_BLACK_OVERLAY = 502
    const val PLAYBACK_SHOW_RADIO_OVERLAY = 503

    const val OVERLAY_FEATURE_VIEW_SHOW = 601
    const val OVERLAY_FEATURE_VIEW_HIDE = 602
    const val OVERLAY_FEATURE_VIEW_INIT = 603
    const val OVERLAY_FEATURE_VIEW_LOAD = 604

    const val DISK_READY_EVENT = 700

    const val SEARCH_CHANNELS_RESULT = 990

    const val SCHEDULED_RECORDING_ADD = 550
    const val SCHEDULED_RECORDING_NOTIFICATION = 551
    const val SCHEDULED_RECORDING_NOTIFICATION_START= 557
    const val SCHEDULED_RECORDING_REMOVED = 552
    const val SCHEDULED_REMINDER_ADD = 553
    const val SCHEDULED_REMINDER_REMOVED = 555


    const val SCHEDULED_REMINDER_NOTIFICATION = 123

    const val USB_DRIVE_FULL = 8998
    const val USB_DEVICE_CONNECTED = 9889
    const val USB_DEVICE_DISCONNECTED = 8989
    const val PVR_RECORDING_IN_PROGRESS = 9989
    const val PVR_RECORDING_FINISHED = 9990
    const val PVR_PLAYBACK_STARTED = 9999
    const val PVR_PLAYBACK_STOPPED = 9998
    const val REFRESH_PVR_BANNER = 7899
    const val RCU_DIGIT_PRESSED = 541
    const val RCU_PERIOD_PRESSED = 542
    const val SDK_POST_INIT_FINISHED = 777

    const val FOCUS_ON_BACK_PRESS = 778

    const val RECORDING_SCHEDULED_TOAST = 556
    const val TESTING_FINISHED = 2319

    const val CHANNEL_CHANGED = 4875
    const val UPDATE_INFO_BANNER = 4876
    const val ACTIVE_AUDIO_TRACK_REFRESHED = 4877
    const val VIDEO_ASPECT_RATION = 5001
    const val RECORDING_RENAMED = 10100
    const val UPDATED_CONFIG_KEYS = 4877

    const val BLUE_MUTE_ENABLED = 11000
    const val NO_SIGNAL_POWER_OFF_ENABLED = 11100
    const val NO_SIGNAL_POWER_OFF_TIME_CHANGED = 11200
}